# This workflow will build a Golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  release:
    types: [created]

jobs:
  build-releases:
    permissions:
      contents: write
      packages: write
      id-token: write
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23' # Specify your Go version here

    - name: Build
      run: |
        mkdir -p bin
        go build -o bin/headers_${{ matrix.goos }}_${{ matrix.goarch }} ./Go

    - name: Upload Release Assets
      uses: actions/upload-artifact@v3
      with:
        name: release-binaries
        path: bin/

    - name: Release Go Binaries
      uses: wangyoucao577/go-release-action@v1.35
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        project_path: "./Go"
        binary_name: "headers_${{ matrix.goos }}_${{ matrix.goarch }}"
        overwrite: true




